import mongoose from 'mongoose';
await mongoose.connect(process.env.MONGODB_URI);
const db = mongoose.connection.db;
const prods = db.collection('products');
const cats = db.collection('categories');
console.log('products total:', await prods.countDocuments());
console.log('active!=false:', await prods.countDocuments({isActive:{$ne:false}}));
const catList = await cats.find({}).project({name:1,slug:1,parent:1}).toArray();
console.log('categories:', catList.length);
const counts = await prods.aggregate([{$group:{_id:'$category',n:{$sum:1}}}]).toArray();
const m = new Map(counts.map(x=>[String(x._id),x.n]));
for (const k of catList) console.log(` - ${k.name} | ${k.slug} | parent=${k.parent?'yes':'no'} | products=${m.get(String(k._id))||0}`);
const s = await db.collection('settings').findOne({key:'homepage_sections'});
console.log('homepage_sections:', s ? JSON.stringify(s.value).slice(0,2500) : 'NONE');
await mongoose.disconnect();
